title: Sazs’ Cricket Blog
author: Shastivel
email: sazcricketblog@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The right place for the analysis of the latest cricket matches.
# social links
twitter_username: sazscricketblog # DO NOT include the @ character, or else the build will fail!
# github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima

timezone: Asia/Kolkata
